### PR TITLE
Update LLVM (MinGW) toolchain

### PR DESCRIPTION
**Pull request by riverar**

### CODE REVIEW

**Comment by riverar** [comment]
Hey @mati865, looks like something is up with gnullvm toolchain?

**Comment by kennykerr** [comment]
Disabled the cross.yml workflow for now.

**Comment by mati865** [comment]
Sorry, one little `cfg` change got lost in the rebase...
Going to open PR fixing it ASAP but don't know how long it will take to get approval.

**Comment by mati865** [comment]
This issue should be fixed in latest nightly (untested). Do you want to try again or should I take care of it?
Related Rust PR: https://github.com/rust-lang/rust/pull/104461

**Review by kennykerr — APPROVED** [review]

**Comment by riverar** [comment]
Thanks @mati865 for the quick action!

**Pull request merged**
