### PR TITLE
Draft support for `VARIANT` and `PROPVARIANT`

### PR DESCRIPTION
**Pull request by kennykerr**
Hey folks, finally spending some time on `VARIANT` and `PROPVARIANT`. This is not quite done but do give me some feedback on the shape of things. Does this seem useful? Exhaustive coverage of the variant types may not be practical, but would this still be useful with partial support?

Fixes: #539

### CODE REVIEW

**Comment by mwcampbell** [comment]
To replace [AccessKit](https://github.com/AccessKit/accesskit)'s current code for constructing `VARIANT`s, this would also need to support `VT_UNKNOWN`. I suppose the next step is to make the generated bindings use the new `VARIANT` wrapper rather than the raw struct, making sure to get ownership transfer right, particularly when a method in a user-implemented interface returns a `VARIANT`, as with `IRawElementProviderSimple::GetPropertyValue` which AccessKit implements.

**Comment by mwcampbell** [comment]
I forgot to say, thanks for this and for all your work on windows-rs. I have no immediate need for this, as I already wrote the ugly code to create `VARIANT`s in AccessKit, but I'm happy to see safe and convenient support for more aspects of the Windows API.

**Comment by kennykerr** [comment]
Thanks @mwcampbell, yes `VT_UNKNOWN` support is on my list. 👍

**Comment by kennykerr** [comment]
Final PR coming soon.

**Comment by kennykerr** [comment]
Final PR is here: #2786

**Pull request closed without merging**
