### PR TITLE
Support standalone code generation

### PR DESCRIPTION
**Pull request by kennykerr**
Even with a choice between the `windows` and `windows-sys` crates, some developers may prefer to use completely standalone bindings. This update introduces the `standalone` function to the `windows-bindgen` crate that provides the ability to generate entirely standalone bindings for Windows APIs with a single function call that you can run from a test to automate the generation of bindings. This can help to reduce your dependencies while continuing to provide a sustainable path forward for any future API requirements you might have, or just to refresh your bindings from time to time to pick up any bug fixes automatically from Microsoft.

Here's an example of how you might use it. Here's what your project's Cargo.toml file might look like:

```
[dependencies.windows-targets]
version = "0.42"

[dev-dependencies]
windows-bindgen = "vnext"
```

The `windows-targets` crate is a lib-only crate that provides import libs for supported targets. This isn't strictly necessary but simplifies importing Windows API functions. `raw-dylib` may also be used to avoid this dependency. The `windows-bindgen` crate is only needed for generating bindings and is thus a dev dependency only.

Given this dev dependency, we can now write a test to generate the bindings as follows:

```rust
#[test]
fn gen_bindings() {
    use windows_bindgen::standalone;

    let apis = [
        "Windows.Win32.System.SystemInformation.GetTickCount",
    ];

    let bindings = standalone(&apis);
    std::fs::write("src/bindings.rs", bindings).unwrap();
}
```

This will generate bindings for the `GetTickCount` function. Running the test will result in the following being generated and written to the `src/bindings.rs` file:

```rust
#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]
pub type PSTR = *mut u8;
pub type PWSTR = *mut u16;
pub type PCSTR = *const u8;
pub type PCWSTR = *const u16;
#[link(name = "windows")]
extern "system" {
    pub fn GetTickCount() -> u32;
}
```

The crate can now make use of these standalone bindings as follows:

```rust
mod bindings;
use bindings::*;

fn main() {
    unsafe {
        println!("{}", GetTickCount());
    }
}
```

Let's now add a call to the `MessageBoxA` function, as a slightly more interesting example. Update the `apis`  array in the test as follows:

```rust
    let apis = [
        "Windows.Win32.System.SystemInformation.GetTickCount",

        "Windows.Win32.UI.WindowsAndMessaging.MessageBoxA",
        "Windows.Win32.Foundation.HWND",
        "Windows.Win32.UI.WindowsAndMessaging.MESSAGEBOX_RESULT",
        "Windows.Win32.UI.WindowsAndMessaging.MESSAGEBOX_STYLE",
    ];
```

This will now generate a bunch of additional bindings so that you can also call `MessageBoxA`:

```rust
fn main() {
    unsafe {
        println!("{}", GetTickCount());

        MessageBoxA(0, "hello\0".as_ptr(), "World\0".as_ptr(), MB_OK);
    }
}
```

The new bindings will look as follows:

```rust
#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]
pub type PSTR = *mut u8;
pub type PWSTR = *mut u16;
pub type PCSTR = *const u8;
pub type PCWSTR = *const u16;
#[link(name = "windows")]
extern "system" {
    pub fn GetTickCount() -> u32;
}
#[link(name = "windows")]
extern "system" {
    pub fn MessageBoxA(
        hwnd: HWND,
        lptext: PCSTR,
        lpcaption: PCSTR,
        utype: MESSAGEBOX_STYLE,
    ) -> MESSAGEBOX_RESULT;
}
pub type HWND = isize;
pub type MESSAGEBOX_RESULT = i32;
pub const IDOK: MESSAGEBOX_RESULT = 1i32;
pub const IDCANCEL: MESSAGEBOX_RESULT = 2i32;
pub const IDABORT: MESSAGEBOX_RESULT = 3i32;
pub const IDRETRY: MESSAGEBOX_RESULT = 4i32;
pub const IDIGNORE: MESSAGEBOX_RESULT = 5i32;
pub const IDYES: MESSAGEBOX_RESULT = 6i32;
pub const IDNO: MESSAGEBOX_RESULT = 7i32;
pub const IDCLOSE: MESSAGEBOX_RESULT = 8i32;
pub const IDHELP: MESSAGEBOX_RESULT = 9i32;
pub const IDTRYAGAIN: MESSAGEBOX_RESULT = 10i32;
pub const IDCONTINUE: MESSAGEBOX_RESULT = 11i32;
pub const IDASYNC: MESSAGEBOX_RESULT = 32001i32;
pub const IDTIMEOUT: MESSAGEBOX_RESULT = 32000i32;
pub type MESSAGEBOX_STYLE = u32;
pub const MB_ABORTRETRYIGNORE: MESSAGEBOX_STYLE = 2u32;
pub const MB_CANCELTRYCONTINUE: MESSAGEBOX_STYLE = 6u32;
pub const MB_HELP: MESSAGEBOX_STYLE = 16384u32;
pub const MB_OK: MESSAGEBOX_STYLE = 0u32;
pub const MB_OKCANCEL: MESSAGEBOX_STYLE = 1u32;
pub const MB_RETRYCANCEL: MESSAGEBOX_STYLE = 5u32;
pub const MB_YESNO: MESSAGEBOX_STYLE = 4u32;
pub const MB_YESNOCANCEL: MESSAGEBOX_STYLE = 3u32;
pub const MB_ICONHAND: MESSAGEBOX_STYLE = 16u32;
pub const MB_ICONQUESTION: MESSAGEBOX_STYLE = 32u32;
pub const MB_ICONEXCLAMATION: MESSAGEBOX_STYLE = 48u32;
pub const MB_ICONASTERISK: MESSAGEBOX_STYLE = 64u32;
pub const MB_USERICON: MESSAGEBOX_STYLE = 128u32;
pub const MB_ICONWARNING: MESSAGEBOX_STYLE = 48u32;
pub const MB_ICONERROR: MESSAGEBOX_STYLE = 16u32;
pub const MB_ICONINFORMATION: MESSAGEBOX_STYLE = 64u32;
pub const MB_ICONSTOP: MESSAGEBOX_STYLE = 16u32;
pub const MB_DEFBUTTON1: MESSAGEBOX_STYLE = 0u32;
pub const MB_DEFBUTTON2: MESSAGEBOX_STYLE = 256u32;
pub const MB_DEFBUTTON3: MESSAGEBOX_STYLE = 512u32;
pub const MB_DEFBUTTON4: MESSAGEBOX_STYLE = 768u32;
pub const MB_APPLMODAL: MESSAGEBOX_STYLE = 0u32;
pub const MB_SYSTEMMODAL: MESSAGEBOX_STYLE = 4096u32;
pub const MB_TASKMODAL: MESSAGEBOX_STYLE = 8192u32;
pub const MB_NOFOCUS: MESSAGEBOX_STYLE = 32768u32;
pub const MB_SETFOREGROUND: MESSAGEBOX_STYLE = 65536u32;
pub const MB_DEFAULT_DESKTOP_ONLY: MESSAGEBOX_STYLE = 131072u32;
pub const MB_TOPMOST: MESSAGEBOX_STYLE = 262144u32;
pub const MB_RIGHT: MESSAGEBOX_STYLE = 524288u32;
pub const MB_RTLREADING: MESSAGEBOX_STYLE = 1048576u32;
pub const MB_SERVICE_NOTIFICATION: MESSAGEBOX_STYLE = 2097152u32;
pub const MB_SERVICE_NOTIFICATION_NT3X: MESSAGEBOX_STYLE = 262144u32;
pub const MB_TYPEMASK: MESSAGEBOX_STYLE = 15u32;
pub const MB_ICONMASK: MESSAGEBOX_STYLE = 240u32;
pub const MB_DEFMASK: MESSAGEBOX_STYLE = 3840u32;
pub const MB_MODEMASK: MESSAGEBOX_STYLE = 12288u32;
pub const MB_MISCMASK: MESSAGEBOX_STYLE = 49152u32;
```

Fixes: #1720

### CODE REVIEW

**Comment by kennykerr** [comment]
Note that this PR only changes the `bindgen` crate. The changes to the `windows` and `windows-sys` code gen are merely whitespace differences due to limitations in `rustfmt`.

**Comment by poliorcetics** [comment]
I wasn’t one of the person asking for it, but still, it looks absolutely amazing, thanks for that !

To avoid recompiling the bindings all the time when building the crate, we could add a recommandation to move them to a sub-crate only for that, for example parking_lot would introduce « parking_lot_bindings_windows » and simply save the bindings in this new crate’s lib.rs.

Are the bindings always windows-sys’ style or is it possible to have them windows’ style in the future (I’m thinking about COM APIs), with added traits and all (probably not for this MR though) ?

**Comment by djc** [comment]
Awesome, looking forward to it!

**Comment by MarijnS95** [comment]
:+1: for having this on `windows`, I already suggested the same (including the mentioned `windows-core` split) in https://github.com/microsoft/windows-rs/issues/1720#issuecomment-1485051109 in hopes of having the best of both worlds: compile-times similar to `windows-sys`, much smaller code size than both crates, _and_ safe(r) and more complete (COM) apis.

**Pull request merged**
