### PR TITLE
Slim doc generation

### PR DESCRIPTION
**Pull request by kennykerr**
While looking into #2665, I found some areas where the doc generation could be simplified. Mainly this removes a bunch of redundant doc comments. And shaves a few hundred thousand lines of code. 😏

### CODE REVIEW

**Comment by tim-weis** [comment]
The *"Required features"* documentation items seem to have dropped the quotation marks around the features. That's unfortunate as it requires extra work to copy them into a *Cargo.toml* file now. It would be nice to have them back unless there is a compelling reason for this change.

**Comment by kennykerr** [comment]
Right, I originally removed them as the italics rendering was causing some problems where the quotes were not plain quotes supported by toml but it seems now that it's not italic that it would work fine so I can add them back.

**Comment by tim-weis** [comment]
Thanks!

For reference, the non-ASCII quotation marks transformation was fixed<sup>*\[citation needed\]*</sup> by wrapping the quoted feature names in backticks (\`). This has worked reliably with and without italics. I liked the italics better, but I can probably be trained to like the new layout no less than the old, familiar formatting, given enough training data.

**Comment by kennykerr** [comment]
Great, the whole docs things has been frustrating and tedious as rustdoc is so problematic that I've forgotten some of the twists and turns. I'm still considering scrapping it in favor of generating docs directly.

**Pull request merged**
