### PR TITLE
Add `no-default-features` yml workflow

### PR DESCRIPTION
**Pull request by kennykerr**
Following up on https://github.com/microsoft/windows-rs/pull/3047#discussion_r1605448388 where @dpaoliello suggested we test crates with no default features.

### CODE REVIEW

**Comment by kennykerr** [comment]
@ChrisDenton here's some more fallout from the `unexpected_cfgs` thing. 

https://github.com/microsoft/windows-rs/actions/runs/9207820449/job/25328694260?pr=3053

**Comment by kennykerr** [comment]
Actually looking closer it might be an unrelated nightly change.

**Comment by ChrisDenton** [comment]
Yeah, I think it's basically saying that `unused_qualifications` is redundant because it's already being set in `rust_2018_idioms`.

**Comment by ChrisDenton** [comment]
Aside: lint changes have been exhausting recently.

**Comment by kennykerr** [comment]
Yes, really losing the value for me.

**Comment by ChrisDenton** [comment]
Oh, looks like you were right the first time. It seems that any group has to be priority -1 even if it doesn't include the lint.

**Comment by kennykerr** [comment]
Yep, that's super confusing.

**Pull request merged**
