### PR TITLE
Update Win32 metadata

### PR DESCRIPTION
**Pull request by kennykerr**
Fixes: #2811

### CODE REVIEW

**Comment by kennykerr** [comment]
@riverar just a heads up that I updated the MSVC libs in https://github.com/microsoft/windows-rs/pull/2812/commits/c3f5af4fa34d7f4779909270063d2000dda26377 locally but since I can't update the other libs locally I grabbed the libs produced by the build and was surprised to see a delta on the msvc lib for arm https://github.com/microsoft/windows-rs/pull/2812/commits/e0e5e09fdc089d23504c0b326cf46a8a5263a748

**Comment by riverar** [comment]
The aarch64 lib in https://github.com/microsoft/windows-rs/commit/c3f5af4fa34d7f4779909270063d2000dda26377 is actually x64, something went awry there.

**Comment by kennykerr** [comment]
Hmm. We need to get GitHub to finally support ARM64.

**Comment by ydirson** [comment]
This PR breaks such code:
```
error[E0277]: the `?` operator can only be applied to values that implement `Try`
 --> src\wmi_extra.rs:5:5
  |
5 |     unsafe { Com::CoInitializeEx(None, Com::COINIT_MULTITHREADED) }?;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `HRESULT`
  |
  = help: the trait `Try` is not implemented for `HRESULT`
```

That does not seem intended, or is it?

**Comment by ydirson** [comment]
Oh, and to return a `Result`, `CanReturnMultipleSuccessValues` would need more work, like generating function-specific enums?

**Pull request merged**
