### PR TITLE
Move to Rust edition 2021 and version 1.56

### PR DESCRIPTION
**Pull request by kennykerr**
Now that the major crate dependencies like `syn` and `tokio` have moved to 1.56 or later, `windows-rs` can finally make the move to the 2021 edition of Rust and MSRV for `windows` and `windows-sys` will be 1.56 from here on.

### CODE REVIEW

**Comment by kennykerr** [comment]
Looks like this is failing due to a change in 2021: https://doc.rust-lang.org/stable/edition-guide/rust-2021/reserving-syntax.html

**Comment by Thomasdezeeuw** [comment]
@TheBlueMatt I don't this that's true, Mio only depends on v0.48, see https://github.com/tokio-rs/mio/blob/8dd37c5e14bf7031365321c5aad5dc85788b9a09/Cargo.toml#L52, Cargo isn't allowed to use v0.49 or v0.50 because of that.

**Comment by kennykerr** [comment]
Hopefully #2613 will help.

**Comment by kennykerr** [comment]
That comment was purely about the fact that Rust 1.48 doesn't support the `version` key.

**Pull request merged**
