### PR TITLE
Address Rust nightly compiler warnings

### PR DESCRIPTION
**Pull request by kennykerr**
Nightly Rust just started lighting up the `improper_ctypes` warning a "type is infinitely recursive" but it seems to be a false positive. 

You can see examples in the build failure here:

https://github.com/microsoft/windows-rs/actions/runs/10997420809/job/30532908394?pr=3291

And here:

https://github.com/microsoft/windows-rs/actions/runs/10997420795/job/30532923854?pr=3291

### CODE REVIEW

**Comment by kennykerr** [comment]
@ChrisDenton do you happen to know if this is a compiler bug? I searched the Rust repo but I couldn't find an issue related to this.

**Comment by kennykerr** [comment]
This update also addresses another unrelated new warning about a `shared reference to mutable static` in a test. https://github.com/microsoft/windows-rs/pull/3292/commits/9863c4d40560439f4e80c6aa69f579a55274541f

**Comment by ChrisDenton** [comment]
Seems like a totally spurious warning. I've opened [an issue](https://github.com/rust-lang/rust/issues/130757). It's being looked into.

**Comment by kennykerr** [comment]
Thanks I left a comment to remove these when that issue is resolved.

**Comment by ChrisDenton** [comment]
A revert has been merged so it should be fixed in the next nightly (aka tomorrow).

**Pull request merged**
