### PR TITLE
0.48.4

### PR DESCRIPTION
**Pull request by kennykerr**
A user reported issues with using Rust 1.48 with `windows-targets`. It is quite difficult to validate as that is such an old version of Rust, but this tweak should address the compatibility concern. 

This just flips `windows-targets` and the arch-specific crates to use Rust edition 2018.

### CODE REVIEW

**Review by Thomasdezeeuw — APPROVED** [review]
Thanks for this @kennykerr

**Review by Darksonn — APPROVED** [review]

**Comment by kennykerr** [comment]
Thanks for checking folks.

**Comment by kennykerr** [comment]
I have published 0.48.4 of `windows-targets` but even now I'm not convinced this actually works. Rust 1.48 is really broken.

When I set `rustup default 1.48` and then build an empty project with a dependency on `windows-targets` it complains about the `resolver`. 🤷‍♂️

**Comment by Darksonn** [comment]
The Cargo.toml that it's using looks like this:
```toml
# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
#
# When uploading crates to the registry Cargo will automatically
# "normalize" Cargo.toml files for maximal compatibility
# with all versions of Cargo and also rewrite `path` dependencies
# to registry (e.g., crates.io) dependencies.
#
# If you are reading this file be aware that the original Cargo.toml
# will likely look very different (and much more reasonable).
# See Cargo.toml.orig for the original contents.

[package]
edition = "2018"
name = "windows-targets"
version = "0.48.4"
authors = ["Microsoft"]
description = "Import libs for Windows"
readme = "readme.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/microsoft/windows-rs"
resolver = "2"

[target.aarch64-pc-windows-gnullvm.dependencies.windows_aarch64_gnullvm]
version = "0.48.4"

[target."cfg(all(target_arch = \"aarch64\", target_env = \"msvc\", not(windows_raw_dylib)))".dependencies.windows_aarch64_msvc]
version = "0.48.4"

[target."cfg(all(target_arch = \"x86\", target_env = \"gnu\", not(windows_raw_dylib)))".dependencies.windows_i686_gnu]
version = "0.48.4"

[target."cfg(all(target_arch = \"x86\", target_env = \"msvc\", not(windows_raw_dylib)))".dependencies.windows_i686_msvc]
version = "0.48.4"

[target."cfg(all(target_arch = \"x86_64\", target_env = \"gnu\", not(target_abi = \"llvm\"), not(windows_raw_dylib)))".dependencies.windows_x86_64_gnu]
version = "0.48.4"

[target."cfg(all(target_arch = \"x86_64\", target_env = \"msvc\", not(windows_raw_dylib)))".dependencies.windows_x86_64_msvc]
version = "0.48.4"

[target.x86_64-pc-windows-gnullvm.dependencies.windows_x86_64_gnullvm]
version = "0.48.4"
```
The `resolver = 2` line is the problem. If the original toml doesn't have it, then you may have to use an older cargo to publish it.

**Comment by kennykerr** [comment]
Thanks, there's no `resolver` in the original toml but there is one in the workspace for `windows-rs`. Older versions of cargo just don't work well or at all within the context of a workspace.

**Comment by Darksonn** [comment]
Yeah, 1.48 CI also caused us a lot of trouble.

**Comment by kennykerr** [comment]
I can fix the 1.48 resolver thing by temporarily deleting the workspace file, publishing, and then restoring it. 

I think I'll do that and publish `windows-targets` 0.48.5 and that will be the final release to support 1.48. 

I will then switch everything in `windows-rs` to use edition 2021 and MSRV 1.56.

**Comment by Darksonn** [comment]
Sounds like a good plan to me.

**Comment by kennykerr** [comment]
All done. `windows-targets` 0.48.5 has been published and I've manually confirmed that it builds fine with Rust 1.48.

**Comment by Thomasdezeeuw** [comment]
Thanks @kennykerr!

**Pull request merged**
