### PR TITLE
Include nested dependencies in standalone code generation

### PR DESCRIPTION
**Pull request by Jake-Shadle**
This PR fixes 2 issues:

- When emitting COM interfaces with `standalone_sys` the type aliases were not pub like everything else.
- Nested types were not being crawled when gathering the types, which would result in fields in nested records that used types that were unique to them to not be emitted

Fixes: #2478
Fixes: #2479

### CODE REVIEW

**Comment by kennykerr** [comment]
Thanks for the fix! Just need to rerun `cargo run -p tool_core` to regenerate the internal bindings. 

> When emitting COM interfaces with standalone_sys the type aliases were not pub like everything else.

The trouble here is that this may introduce name collisions. I'm not opposed to changing it, but we'd need to be a bit more explicit in `windows-core` about how we refer to those bindings.

**Comment by Jake-Shadle** [comment]
Oof, yah, that broke everything.

**Comment by kennykerr** [comment]
I can fix that up in a separate PR if you'd prefer. Let me know.

**Comment by kennykerr** [comment]
Sounds good - I can find a prettier solution separately.

**Pull request merged**
