### PR TITLE
Disable signature transformation for `NTSTATUS`

### PR DESCRIPTION
**Pull request by kennykerr**
Fixes: #2656

### CODE REVIEW

**Comment by riverar** [comment]
I don't think there are enough `STATUS_PENDING` returning functions to warrant degrading the developer experience here. Is there something preventing us from specializing the return transformation for `NTSTATUS`?

**Comment by kennykerr** [comment]
I think the issue is that there are many many more success codes when it comes to `NTSTATUS` compared with say `HRESULT`. 

The alternative would be to return `Result<NTSTATUS, Error>` but that would be very different to the way we handle error transformations today and just seems like it would cause more confusion than anything else.

**Comment by ChrisDenton** [comment]
The status quo relies on `CanReturnMultipleSuccessValues` being accurately applied (or not) to all NTSTATUS returning functions. Otherwise the experience is not just degraded, it's unusable for certain scenarios. But I think we simply don't have the people to ensure that the metadata 100% accurately applies the attribute. Maybe that'll come in time but we're not there yet.

So, all else aside, I think something has to change.

**Comment by riverar** [comment]
Agree we'd just be applying `CanReturnMultipleSuccessValues` to functions as we find them, but in the absence of more data demonstrating a large swath of functions that will be better off, we may want to consider it over regressing the experience across the board. I recognize, though, getting that data is probably not possible in the short term and concede as a result.

**Comment by ChrisDenton** [comment]
I guess there are alternatives but they'll require more work to get started on. So maybe the opposite attribute for `NTSTATUS` would be more useful (e.g. `CanReturnSingleSuccessValues`)? Have the least destructive behaviour by default and only apply `Result` ergonomics for functions that have been reviewed as only returning one success value.

**Comment by kennykerr** [comment]
I just don't think any of these attribute-based approaches are scalable.

**Comment by kennykerr** [comment]
Unrelated, the build is failing on the diff check for libs. That's probably because GitHub updated their MSVC toolchain and now the libs have a different version stamp again. I really need to get that version stamp wiped out.

**Review by ChrisDenton — DISMISSED** [review]

**Comment by riverar** [comment]
> Unrelated, the build is failing on the diff check for libs. That's probably because GitHub updated their MSVC toolchain and now the libs have a different version stamp again. I really need to get that version stamp wiped out.

Yup, will pick this up (removing the compiler ID per last discussion).

**Comment by kennykerr** [comment]
Manually updated the libs to unblock this PR.

**Pull request merged**
