### PR TITLE
Add feature search links

### PR DESCRIPTION
**Pull request by kennykerr**
Still need to add support for versioned links, but this is basic idea. 

Fixes: #2717

### CODE REVIEW

**Comment by ChrisDenton** [comment]
The functionality works great for me for the types I've tried. Only minor issue is that on mobile the website is just slightly too wide for more phone. Maybe the version selection box could drop below or above the input on narrow screens?

A possible future enhancement would be to have some way to input a list of types and get a unified list of features rather than entering them one at a time. But I think that's one for the suggestion box and not something that needs thinking about now.

**Comment by kennykerr** [comment]
We could scrap the drop down if the target is configurable via the URL.

**Comment by riverar** [comment]
Adjusted the branch drop-down so it wraps on mobile. Still more work to be done here (e.g. perhaps we shift into a two-inner-row per row layout) but something we can address a bit later.

image

**Comment by tim-weis** [comment]
That looks like a workable solution.

The only suggestion I have is to add a "Copy to clipboard" button. That's not something that needs immediate attention, and could be incorporated at a later time.

**Comment by tim-weis** [comment]
Well, maybe I lied. A cup of coffee later I was reminded about a few more suggestions I had in mind:

* Provide a link to the Rust documentation. I don't know how feasible that is, but it would be convenient to have a quick way to navigate to the signature/type information.
* Provide a link to the MSDN reference documentation. That would need a bit of work but it would be very handy to have.
* Improve the relevance priority in searches. As an example, typing `createprocess` into the search field has the `CreateProcessW` API listed way down. Prioritizing exact (prefix) matches might work better.

I don't know how others feel about those suggestions, but they would definitely streamline *my* workflow.

At any rate, thank you for putting this together and reminding me that a browser-based search doesn't *have to* stall the browser window.

**Comment by riverar** [comment]
All great suggestions, will def. work on those.

**Pull request merged**
