### PR TITLE
Split out type crawling

### PR DESCRIPTION
**Pull request by Jake-Shadle**
This PR splits out type crawling into a separate function and makes `standalone_imp` public so that the user can do the type crawling in a separate pass before emitting them via `standalone_imp`.

Initially I only did this so that the user can query the set of types that will be emitted, but I then encountered the bug described in microsoft/win32metadata#1554 and rolled in a fix that takes advantage of the split out type crawling, while preserving the current behavior of the other `standalone_` functions.

Since I found this one `VK_F` case, I have to assume there are others given the scope of the Win32 API, but I wasn't sure if there were cases where classes or interfaces could clash with functions/constants thus I only have the 3 different variants.

Another possible option would be more narrowly focused on enum constants, where the enum's name could be followed by `::<enum variant>` rather than just `.<enum variant>` as it is now, but I wasn't sure if there might be other cases where a clash could occur between eg. a struct and a function which that fix would not address.

Fixes: microsoft/win32metadata#1554

### CODE REVIEW

**Comment by kennykerr** [comment]
Thanks, but I'd prefer not to complicate the standalone code generation's interface if we can help it. Hopefully https://github.com/microsoft/win32metadata/issues/1554 can be addressed and make this unecessary. Otherwise, I'd like to find an automatic way to handle such collisions so that it "just works".

**Comment by kennykerr** [comment]
Since this should be a rare issue, I simple workaround could be just to emit all overloads. Rust will be happy with that. What do you think?

**Comment by Jake-Shadle** [comment]
That'd be fine I suppose, they can just be manually edited to remove the unneeded items in those rare cases.

**Comment by kennykerr** [comment]
Here you go: #2486

**Pull request closed without merging**
