### PR TITLE
Simpler signature generation

### PR DESCRIPTION
**Pull request by kennykerr**

### CODE REVIEW

**Comment by MarijnS95** [comment]
Hi @kennykerr,

This PR unfortunately makes it so that my local bindings to DirectXShaderCompiler revert back to not using the "QueryInterface"-like function signature, thanks to the [detection of `_COM_Outptr`](https://github.com/microsoft/win32metadata/blob/2c83a3893d83d9800a781ddc2066e56fa9523721/sources/ClangSharpSourceToWinmd/MetadataSyntaxTreeCleaner.cs#L706-L710) which is [missing from DXC](https://github.com/microsoft/DirectXShaderCompiler/blob/cb485263b75495015e2a77cc438e72dc813ea287/include/dxc/dxcapi.h#L75-L88). Before I go ahead and PR this annotation to their headers, do you happen to know what is meant by `While this function is similar to CoCreateInstance, there is no COM involvement.` and if this could possibly be the reason for omitting this annotation, since it is generally applied consistently elsewhere?
Also, since it may take quite some time for these headers to go from git repository -> DXC release -> Windows SDK release -> wind32metadata bindings, would it make sense to push the changes as overrides to win32metadata too? Is there a process in place to remove superfluous overrides from win32metadata again when the header changes trickle in?

Secondly, where can I find some documentation on using `_COM_Outptr_` vs `_COM_Outptr_result_maybenull_`? There are many cases where the output can be null, but only if an error is returned; that doesn't count for `result_maybenull_` right? Then there's also `_Outptr_result_nullonfailure_` but that doesn't imply `COM` objects.

PS: The title of this PR doesn't match the commit that was merged, making it harder to find and identify in my list of tabs. Can you update it to reflect that?

**Comment by MarijnS95** [comment]
> Hi @kennykerr,
> 
> This PR unfortunately makes it so that my local bindings to DirectXShaderCompiler revert back to not using the "QueryInterface"-like function signature, thanks to the [detection of `_COM_Outptr`](https://github.com/microsoft/win32metadata/blob/2c83a3893d83d9800a781ddc2066e56fa9523721/sources/ClangSharpSourceToWinmd/MetadataSyntaxTreeCleaner.cs#L706-L710) which is [missing from DXC](https://github.com/microsoft/DirectXShaderCompiler/blob/cb485263b75495015e2a77cc438e72dc813ea287/include/dxc/dxcapi.h#L75-L88). Before I go ahead and PR this annotation to their headers, do you happen to know what is meant by `While this function is similar to CoCreateInstance, there is no COM involvement.` and if this could possibly be the reason for omitting this annotation, since it is generally applied consistently elsewhere?
> Also, since it may take quite some time for these headers to go from git repository -> DXC release -> Windows SDK release -> wind32metadata bindings, would it make sense to push the changes as overrides to win32metadata too? Is there a process in place to remove superfluous overrides from win32metadata again when the header changes trickle in?
> 
> Secondly, where can I find some documentation on using `_COM_Outptr_` vs `_COM_Outptr_result_maybenull_`? There are many cases where the output can be null, but only if an error is returned; that doesn't count for `result_maybenull_` right? Then there's also `_Outptr_result_nullonfailure_` but that doesn't imply `COM` objects.
> 
> PS: The title of this PR doesn't match the commit that was merged, making it harder to find and identify in my list of tabs. Can you update it to reflect that?

Thanks for looking into this!

**Comment by kennykerr** [comment]
As I've steadily improved the accuracy of parsing I discovered that there are some functions that looked like the QueryInterface pattern but were not in fact returning interfaces at all. That's why I had to tighten up the heuristic for signature detection. 

> While this function is similar to CoCreateInstance, there is no COM involvement.

The DirectX APIs don't rely on combase for activation and don't rely on COM apartments at all. That is generally what is meant by such comments. DirectX still relies on COM in the sense that COM interfaces are used and all the normal rules around IUnknown queries and lifetimes are still enforced. So the _COM_Outptr_ annotation is still appropriate. 

I think it would make sense to update the DX headers and also update the win32metadata project in the short term with some kind of fixup so that this works today.

> Secondly, where can I find some documentation on using _COM_Outptr_ vs _COM_Outptr_result_maybenull_? 

I don't know about documentation but DirectX does rely on the latter quite a lot for feature detection e.g. would some expensive object creation succeed with these flags? That's still something I need to support in Rust but may end up dropping the QueryInterface-like support in such cases. #737

I've updated the title to match the resulting commit.

**Comment by MarijnS95** [comment]
> As I've steadily improved the accuracy of parsing I discovered that there are some functions that looked like the QueryInterface pattern but were not in fact returning interfaces at all. That's why I had to tighten up the heuristic for signature detection.

Yeah, that's great :slightly_smiling_face: 

> > While this function is similar to CoCreateInstance, there is no COM involvement.
> 
> The DirectX APIs don't rely on combase for activation and don't rely on COM apartments at all. That is generally what is meant by such comments. DirectX still relies on COM in the sense that COM interfaces are used and all the normal rules around IUnknown queries and lifetimes are still enforced. So the _COM_Outptr_ annotation is still appropriate.

Thanks for confirming my thoughts!

> I think it would make sense to update the DX headers and also update the win32metadata project in the short term with some kind of fixup so that this works today.

Great, I can take care of both over the course of some time; will need to check how many (public-facing) functions are affected.

> > Secondly, where can I find some documentation on using _COM_Outptr_ vs _COM_Outptr_result_maybenull_?
> 
> I don't know about documentation but DirectX does rely on the latter quite a lot for feature detection e.g. would some expensive object creation succeed with these flags? That's still something I need to support in Rust but may end up dropping the QueryInterface-like support in such cases. #737

At least for the most important `DxcCreateInstance` there are no flags. I expect to either receive an error (ie. `REGDB_E_CLASSNOTREG`), or `S_OK` and a valid pointer. If that is the case `result_maybenull` should not be used, right?
For the other cases I'll take this up with the DXC maintainers; they should be able to point me in the right direction if I fail to analyze the functions properly, as long as I've got the conventions right.

**Pull request merged**
