### PR TITLE
Hash impl for HSTRING

### PR DESCRIPTION
**Pull request by zardini123**
Adds Hash implementation to HSTRING.

### CODE REVIEW

**Comment by kennykerr** [comment]
Thanks for the contribution! Please add a basic test here just to make sure we have a test that validates:

`crates\tests\core\tests\hstring.rs`

**Comment by zardini123** [comment]
@microsoft-github-policy-service agree

**Comment by zardini123** [comment]
@microsoft-github-policy-service agree

**Comment by zardini123** [comment]
Hi @kennykerr!  Thank you for the feedback.  I have created two tests to validate the API of hashing HSTRING and updated my branch.

Let me know if there is any more needed changes or feedback.

**Pull request merged**
