### PR TITLE
yml: Clean up formatting and indetation

### PR DESCRIPTION
**Pull request by MarijnS95**
YAML arrays should have one extra indent level on top of their parent, before starting the line with `-`.  In addition the YAML formatter seems to prefer double quotes over single quotes, and is used this way in all but three places.  Finally, trim some trailing whitespace and make sure all files have a single trailing newline.

### CODE REVIEW

**Review by rylev — APPROVED** [review]
Looks good. It would be nice if we could enforce this formatting somehow...

**Comment by MarijnS95** [comment]
@rylev it was initially a random vscode extension that calls a formatter executable, I can probably figure out which one it is and/or if it's already in GitHubs virtual-environments for consumption.

**Comment by MarijnS95** [comment]
@rylev `yamllint` works well for this purpose and is preinstalled in GitHub's `virtual-environment`. This particular command has a nonzero exit code on `master` (https://github.com/MarijnS95/windows-rs/runs/7185456072?check_suite_focus=true#step:3:7), but clean output on this PR:

```
yamllint -f github -d "{extends: relaxed, rules: {line-length: {max: 1000}}}" .
```

Note that `-f github` makes it emit [nice annotations](https://github.com/MarijnS95/windows-rs/actions/runs/2611851905) :+1: 

Shall I push that as a separate PR too?

**Comment by MarijnS95** [comment]
Thanks @kennykerr! Do you want the `yamllint` as a CI step too?

**Comment by MarijnS95** [comment]
@kennykerr I can't comment on that - feel fry to try it out and let me know! I have the branch ready regardless, can easily PR it.

**Comment by MarijnS95** [comment]
@kennykerr Have you checked this yet? I'd be happy to submit https://github.com/microsoft/windows-rs/compare/master...MarijnS95:windows-rs:yamllint if this works for you :)

**Comment by rylev** [comment]
FYI: the following for me worked for installing the command in Windows: `py -m pip install yamllint`

**Pull request merged**
