### PR TITLE
Add work around for bug in cross compilation

### LINKED ISSUE #614: Rust docs broken
Just leaving this issue here as a few people have asked. There are two separate issues. 

The [Windows crate docs](https://docs.rs/crate/windows/0.5.0) are broken due to [this rustc bug](https://github.com/rust-lang/rust/issues/82991). 

The [generated documentation](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/) hasn't been updated because `cargo` hangs trying to build [windows-docs-rs](https://github.com/microsoft/windows-docs-rs). I seem to have hit some kind of limit, but its not clear what's wrong. `rustc` allocates about 5 GB and then `cargo` hangs inside `git_refdb_backend_fs`. This happens reliably. [Here's a repro](https://github.com/microsoft/windows-rs/files/6165754/build.zip) if you want to play along.

Running out of memory while the CPU idles is kind of sad. 😢 Here is stable/night/nightly-2021-03-16 running in parallel:

image

In all three cases, the hang happens here:

image

### PR DESCRIPTION
**Pull request by rylev**
This should fix #614. I can now successfully document windows-rs on Linux against the `x86_64-pc-windows-msvc` target.

### CODE REVIEW

**Comment by jyn514** [comment]
So, I looked at this some more this morning, and something very strange is going on:
- On NixOS, with rustc 1.52.0-nightly (1705a7d64 2021-03-18), `cargo doc --no-deps` panics while compiling `windows_gen`
- On Debian 10, with the same version of nightly, `cargo doc --no-deps` works fine.
- On NixOS, with rustc 1.51.0-beta.8 (73f48e5f6 2021-03-18), `cargo doc --no-deps` works fine.
- On NixOS with this change, I get an error:
```
error: /nix/store/9rabxvqbv0vgjmydiv59wkz768b5fmbc-glibc-2.30/lib/libc.so.6: version `GLIBC_2.32' not found (required by /home/joshua/windows-rs/target/debug/deps/libwindows_gen_macros-c30ffbab983c7445.so)
 --> crates/gen/src/lib.rs:2:1
  |
2 | extern crate windows_gen_macros as macros;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by rylev** [comment]
@jyn514 The libc error is strange. Does a "hello, world" app compile file?

**Comment by jyn514** [comment]
> @jyn514 The libc error is strange. Does a "hello, world" app compile file?

Hello world works but installing `cargo bisect-rustc` does not, so this is probably an environment problem. Weird that it only shows up on nightly.

What OS are you using to compile? It seems weird that this works on Debian 10 but ICEs on NiXOS.

**Comment by rylev** [comment]
I'm compiling on Windows 10 and WSL with an Ubuntu environment. I'm assuming you get this when you cargodoc is running and not while building. Can you try breaking up the build and run step into two?

**Comment by jyn514** [comment]
No, I get this error while building, not documenting.
```

[joshua@uhura:~/windows-rs]$ git checkout FETCH_HEAD
HEAD is now at 59557f0 Merge branch 'master' into fix-cross-compilation

[joshua@uhura:~/windows-rs]$ cargo check
   Compiling windows_gen v0.5.0 (/home/joshua/windows-rs/crates/gen)
error: /nix/store/9rabxvqbv0vgjmydiv59wkz768b5fmbc-glibc-2.30/lib/libc.so.6: version `GLIBC_2.32' not found (required by /home/joshua/windows-rs/target/debug/deps/libwindows_gen_macros-c30ffbab983c7445.so)
 --> crates/gen/src/lib.rs:2:1
  |
2 | extern crate windows_gen_macros as macros;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[joshua@uhura:~/windows-rs]$ cargo check
   Compiling windows_gen v0.5.0 (/home/joshua/windows-rs/crates/gen)
thread 'rustc' panicked at 'Failed to get crate data for crate19', compiler/rustc_metadata/src/creader.rs:136:32
```

**Review by kennykerr — APPROVED** [review]

**Comment by kennykerr** [comment]
Hopefully the actual bug will get fixed but this does unblock x86 builds in my experience as well.

**Comment by kennykerr** [comment]
And just to be clear, this workaround is for the `rustc` cross compilation bug but does not address the `cargo` hang bug mentioned in https://github.com/microsoft/windows-rs/issues/614.

**Pull request merged**
