### PR TITLE
Consolidate code generation

### PR DESCRIPTION
**Pull request by kennykerr**
This update moves all of the code generation features into the `riddle` tool. This includes:

* `windows` and `windows-sys` crate generation
* third-party crate generation
* component development (DLLs)
* standalone code generation

This should greatly simplify the way developers consume bindings and provides a more declarative tool for specifying which bindings to generate and how.

In addition, `riddle` is the tool that can both parse and generate .idl and .winmd files so developers have a single tool for all metadata processing. This part is still very much in development, but this consolidation means I can now focus on a single metadata engine and more quickly bring this to life. 

Note that a few changes will impact existing developers:

* The `windows-bindgen` crate is no more. You can migrate to the `riddle` tool which does all of the same things without requiring you to write code. Whether its standalone code generation or component development, `riddle` provides a simpler way to generate those bindings. It will be published to crates.io so that you can install it using `cargo install riddle`.
* The `windows-metadata` crate has been trimmed down and represents a low-level reader. Generally, you shouldn't have to interact with this crate directly and can just use `riddle`. In particular, the crate no longer embeds the .winmd files for the Windows API. This has two main benefits. The first is that the crate itself is much smaller and the second is that it means you can more easily target whatever metadata your project is built and tested for rather than whatever version windows-rs happens to contain at any given time.

### CODE REVIEW

**Comment by MarijnS95** [comment]
> * It will be published to crates.io so that you can install it using `cargo install riddle`.

(Without looking at the code) curious if this still allows users to consume `riddle` in their `build.rs` as a library crate?

**Comment by kennykerr** [comment]
You can call `riddle` from `build.rs` via `std::process::Command`.

**Comment by MarijnS95** [comment]
And that requires a `build.rs` to call `cargo install riddle` first and clobber the users' environment?

**Comment by kennykerr** [comment]
That depends on how you've chosen to configure the build and prepare the crate for publication.

**Comment by kennykerr** [comment]
I'll write more about the available options when I'm closer to publishing riddle itself.

**Comment by MarijnS95** [comment]
As expected I've added a `cargo install riddle --git my-fork` to my CI scripts now.

**Comment by Marerc** [comment]
Hi, there, thank you for the contributions, your works really help. And is there any toturial for the riddle?

**Comment by kennykerr** [comment]
I'm just polishing it up some more before I publish the version at which point I'll be sure to add a tutorial here:

https://kennykerr.ca/rust-getting-started

**Comment by djc** [comment]
Is there a particular reason there is no library interface for riddle, just a CLI interface?

**Comment by kennykerr** [comment]
That was briefly discussed in #2492 - I'm not strongly opposed but there wasn't a very strong argument for it, so I haven't prioritized that work. Feel free to open a new issue if you have a good case for it.

**Pull request merged**
