### PR TITLE
Add `raw-dylib` testing with `nightly-i686-pc-windows-gnu`

### PR DESCRIPTION
**Pull request by kennykerr**
This should now work thanks to https://github.com/rust-lang/rust/issues/104453 being closed.

### CODE REVIEW

**Comment by kennykerr** [comment]
Hmm, seems something is still not working with `raw-dylib` on `nightly-i686-pc-windows-gnu`.

**Comment by wesleywiser** [comment]
@kennykerr You might want to retry this with the latest nightly build now that https://github.com/rust-lang/rust/pull/107360 has landed.

**Comment by kennykerr** [comment]
@wesleywiser I reran but it still fails with the same error.

**Comment by kennykerr** [comment]
@dpaoliello suggested it might be https://github.com/rust-lang/rust/issues/99534

**Comment by mati865** [comment]
DLL mismatch wouldn't cause `error adding symbols: File format not recognized` error.

**Comment by riverar** [comment]
I have never been successful with the self-contained GNU tools that ships with the tier 1 GNU targets. Switched to using the external tooling.

**Comment by kennykerr** [comment]
Thanks @riverar!

**Pull request merged**
