### PR TITLE
Support query-optional signatures

### LINKED ISSUE #737: Cannot call QueryInterface-like APIs with "NULL" for the ppv parameter
For example, many D3D12 APIs, such as D3D12CreateDevice, operate in a mode where the runtime validates parameters if NULL is passed for the ppv parameter.  Apps often use this to probe whether or not a particular adapter meets their needs, but without performing the heavy-weight, driver-loading, work required to construct and then destruct the object.

See for example https://github.com/microsoft/DirectX-Graphics-Samples/blob/cab614fc3b2ac880f1909c40a485423649940b0d/Samples/Desktop/D3D12HelloWorld/src/HelloWindow/DXSample.cpp#L97

### PR DESCRIPTION
**Pull request by kennykerr**
Distinguishes between query-like signatures - with trailing `GUID*, void**` - and those that are marked optional in metadata (mostly Direct3D). 

This necessitates a move back to explicit generic type parameters as Rust doesn't allow you to mix `impl Trait` parameters with explicit generic call-sites. 

Fixes #737 cc @damyanp 

For example, you can call `D3D12CreateDevice` as follows:

```rust
D3D12CreateDevice::<_, ID3D12Device>(adapter, D3D_FEATURE_LEVEL_11_0, std::ptr::null_mut())?;
```

Or like this:

```rust
let mut device: Option<ID3D12Device> = None;
D3D12CreateDevice(adapter, D3D_FEATURE_LEVEL_11_0, &mut device)?;
```

### CODE REVIEW

**Comment by MarijnS95** [comment]
@kennykerr Note that there's also:

```rust
D3D12CreateDevice(adapter, D3D_FEATURE_LEVEL_11_0, std::ptr::null_mut::<Option<ID3D12Device>>())?;
```

But that's probably uncomfortable enough to "necessitate" explicit type parameters at the call-site instead?

**Comment by kennykerr** [comment]
Yes, I considered that but it just seemed so contrived.

**Comment by MarijnS95** [comment]
The current method at least leaves room to either use a turbofish on the function call, or the `null_mut` allowing to get rid of the `_` substitution for the generic lifetime.

**Comment by kennykerr** [comment]
The `_` is for the first parameter which expects an `impl Trait` - I had to switch from `impl Trait` code gen to explicit type parameters sadly.

**Comment by kennykerr** [comment]
Look at the diff for `bindings.rs` in this PR.

**Comment by MarijnS95** [comment]
Right it reads `_` not `'_`.

**Pull request merged**
