### PR TITLE
Improve `windows-bindgen` for `std` usage 

### PR DESCRIPTION
**Pull request by kennykerr**
As discussed in #2609, this update makes the following changes:

* Strips out comments from response files.
* Removes the special case for `SOCKET`

### CODE REVIEW

**Comment by kennykerr** [comment]
Sweet, thanks for checking!

**Comment by kennykerr** [comment]
@ChrisDenton I'm preparing a release.

**Comment by ChrisDenton** [comment]
Great! My PR should be ready to go once that's done (give or take some minor tweaks).

**Comment by klensy** [comment]
Wait a second, maybe fix for https://github.com/microsoft/win32metadata/issues/1680 can be here too?

**Comment by kennykerr** [comment]
I'd need another release of the Win32 metadata. I don't think there is one yet with that change. That would also mean a breaking change to the API surface so unless that's really urgent I'd prefer to hold off on that. Thoughts?

**Pull request merged**
