### PR TITLE
Adjust license placement for GitHub auto-detection

### PR DESCRIPTION
**Pull request by riverar**
License name/location adjustments:
* Moved both licenses to root for `licensee` [detection](https://github.com/licensee/licensee/blob/master/docs/what-we-look-at.md) used on GitHub
* Renamed licenses to include [GitHub license qualifiers](https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#searching-github-by-license-type)

Example `licensee` output:

```
License:        NOASSERTION
Matched files:  license-apache-2.0, license-mit
license-apache-2.0:
  Content hash:  bec905d850e7f5dc2e2db78a950d4a9db560a0b8
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       Apache-2.0
license-mit:
  Content hash:  dbe99a5ac2dd399218976e1e513aec525c4d56f3
  Attribution:   Copyright (c) Microsoft Corporation.
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
```

### CODE REVIEW

**Comment by riverar** [comment]
Converted to draft, need to double-check GitHub handles the `NOASSERTION` (see output above) in dual license scenarios.

**Comment by riverar** [comment]
Works. Live demo https://github.com/riverar/windows-rs.

**Review by kennykerr — APPROVED** [review]
Thanks!

**Review by kennykerr — APPROVED** [review]

**Comment by kennykerr** [comment]
Neat thanks!

image

**Pull request merged**
