### PR TITLE
Derive `Copy`, `Clone`, and `Debug` for handles

### PR DESCRIPTION
**Pull request by kennykerr**
This just reduces code gen and improves readability.

### CODE REVIEW

**Comment by kennykerr** [comment]
Both #3015 and #3016 are failing with this GNU dlltool error:

https://github.com/microsoft/windows-rs/actions/runs/8924805385/job/24511973178?pr=3015

Unrelated to this change I believe. Any idea what this might be about? Perhaps a change to the GitHub runners?

@riverar @jeremyd2019 @mati865

**Comment by mati865** [comment]
Looks like GHA have changed somehow:
```
C:\msys64\mingw32\bin\dlltool.exe ... -m i386:x86-64
```
32-bit dlltool cannot create x86_64 import libraries.

**Comment by riverar** [comment]
Looping in @mati865 for awareness, as they have some dlltool work in the pipe https://github.com/rust-lang/rust/pull/124138

**Comment by riverar** [comment]
`dlltool.exe` is normally located [by explicitly scouring `PATH`](https://github.com/jfgoog/rust/blob/master/compiler/rustc_codegen_llvm/src/back/archive.rs#L443), which probably got re-ordered in a GHA runner update.

So I suspect adding an explicit dlltool configuration should help here. Let's give it a shot.

**Comment by mati865** [comment]
On the second thought, failing test runs on x86_64 host but targets i686. But it's a proc macro so it should still build for the host.

It could really be a regression then.

**Comment by riverar** [comment]
We manually prepend `C:\msys64\mingw32\bin` onto the path when targeting i686-pc-windows-gnu, not taking proc macros into consideration. So I think the build failure makes more sense to me than the previous successes.

**Comment by mati865** [comment]
Ah, makes sense then. Previous success doesn't make sense though 😄 

It'd probably work if you set PATH to `/mingw64/bin:/mingw32/bin:$PATH` for cross-compilation builds since 64-bit dlltool can generate both kinds of libraries and the linker is called with a target triple prefix.

**Comment by tim-weis** [comment]
Should handle types also `#[derive(PartialOrd, Ord)]` so they can be stored as keys in `BTreeSet`s/`BTreeMap`s? Likewise, `#[derive(Hash)]` would make them eligible as the key in `HashSet`s/`HashMap`s.

**Comment by kennykerr** [comment]
Note that this PR isn't adding these traits - it's merely deriving them rather than generating them directly.

**Pull request merged**
